#ifndef GLOBALS
#define GLOBALS

#define SCREEN_WIDTH 1800
#define SCREEN_HEIGHT 900
#define CLEAR_COLOR 0.0f, 0.0f, 0.0f, 1.0f

#define TRAINING_PERCENTAGE 5.0f/6.0f
#define VALIDATION_PERCENTAGE 1.0f/6.0f

#define IMAGE_SIZE 784 // 28 * 28
#define NUM_HIDDEN_LAYERS 1
#define HIDDEN_LAYER_1 30
#define HIDDEN_LAYER_2 0
#define OUTPUT_LAYER 10

#define TRAINING_RATE 0.1f
#define MINI_BATCH_SIZE 25
#define REGULARIZATION_PARAMETER 5.0f
#define EPOCHS 10

#define POOLING_WINDOW 4

#define HISTOGRAM_SIZE ImVec2(500, 200)

#endif //!GLOBALS